[package]
name = "docksy"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client", "unstable"] }
wayland-backend = "0.3"
log = "0.4"
env_logger = "0.10"
